### PR TITLE
Don't install unavailable versions

### LINKED ISSUE #48: Cpackget is installing a wrong pack version
**Describe the bug**
Cpackget should raise an error when specifying a minimum version that does not exist

**To Reproduce**
```bash
$ cpackget pack add "ARM::CMSIS>=10.0.0"
I: Using pack root: "../packroot"
I: Adding pack "ARM::CMSIS>=10.0.0"
I: Extracting files to ../packroot/ARM/CMSIS/5.8.0 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (8133/8133, 7742 it/s)
```

**Expected behavior**
I think in this case, the expected behavior should be an error message saying that the desired version is not available in any PDSC file

### PR DESCRIPTION
**Pull request by lud0v1c**
Fixes #48. As described in the issue:

- local_repository.idx is now checked first and foremost when listing/checking for installed pack versions
- Trying to install a version (such as >= or @~) that is not available won't install the latest version, but will throw an error and tell the user what's the "closest" version there is.

### CODE REVIEW

File: cmd/installer/pack.go [hunk 1]
```diff
@@ -467,6 +472,13 @@ func (p *PackType) resolveVersionModifier(pdscXML *xml.PdscXML) {
 			return
 		}
 	}
+
+	// No minimum version exists to satisfy target version
+	if p.versionModifier == utils.GreaterVersion && p.targetVersion == "" {
+		log.Errorf("Tried to install atleast version %s, highest available version is %s", p.Version, pdscXML.LatestVersion())
```
Comment (chaws) [inline cmd/installer/pack.go]: "atleast" -> "at least"

**Comment by chaws** [comment]
Just a minor typo, but the PR is good to go! Thanks @lud0v1c for the PR, this one was a bit trickier :)
