### PR TITLE
installer: fix pack name/version regex

### LINKED ISSUE #143: cpackget does not accept pack names starting with numbers
**Describe the bug**
When adding a pack having a name starting with numbers, such as `32L4R9IDISCOVERY_BSP`, an error is returned.

**To Reproduce**
Run the cpackget with the following args:
```
$ cpackget pack add Keil::32L4R9IDISCOVERY_BSP
```
See the error:
```
I: Using pack root: "C:\Temp\packs"
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
```
**Expected behavior**
The pack should be downloaded and installed, no error should be returned.

**Environment (please complete the following information):**
 - OS: windows
 - Version v0.9.0

**Additional context**
It seems to be related to an incorrect regular expression `[a-zA-Z][0-9a-zA-Z_\-]+` in the name pattern:
https://github.com/Open-CMSIS-Pack/cpackget/blob/v0.9.0/cmd/utils/packs.go#L19

**Additional suggestion**
When adding a pack list file as in the following example, the combined output may be misleading concerning which pack is actually failing:
```
$ cat packs.txt
ARM::CMSIS
Keil::32L4R9IDISCOVERY_BSP

$ cpackget add -af packs.txt
I: Using pack root: "C:\Temp\csolution_test\packs\repository"
I: Parsing packs urls via file packs.txt
I: Adding pack "ARM::CMSIS"
I: Extracting files to C:\Temp\csolution_test\packs\repository\ARM\CMSIS\5.9.0...
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
```
For this reason I also suggest to improve the error messages.

### PR DESCRIPTION
**Pull request by lud0v1c**
Fixes the used regular expression for a pack's name and vendor, which didn't match the current specification. Also adds a more varied selection of incorrect strings to test against.

Closes #143.

### CODE REVIEW

**Comment by lud0v1c** [comment]
Thanks to @JonatanAntoni's work, [PR builds](https://github.com/Open-CMSIS-Pack/cpackget/actions/runs/4128126146) are now available.

File: cmd/utils/packs.go [hunk 1]
```diff
@@ -14,15 +14,15 @@ import (
...
+// namePattern specifies a regular expression that matches Pack and Vendor names.
+// Ref: https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/4e2ef7dddc4bcd2a43b530d79908720c9c52da9e/schema/PACK.xsd#L1659
+var namePattern = `[\-_A-Za-z0-9]+`
 
 // nameRegex has a pre-compiled namePattern ready for use
 var nameRegex = regexp.MustCompile(fmt.Sprintf("^%s$", namePattern))
 
 // versionPattern validates pack version.
-// Ref: https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Utilities/PackIndex.xsd
+// Ref: https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/4e2ef7dddc4bcd2a43b530d79908720c9c52da9e/schema/PACK.xsd#L1672
```
Comment (jkrech) [inline cmd/utils/packs.go:25]: Are you keen on a specific version of PACK.xsd or where we should track against? 
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L1671?

**Review by jkrech — APPROVED** [review]
Looks good to me. I tried the cached build artifact to install:
`Keil.32L4R9IDISCOVERY_BSP`
This now works as expected.

File: cmd/utils/packs.go (hunk 1 above)
Comment (lud0v1c) [reply cmd/utils/packs.go:25]: Not necessarily, I just updated the URL as the existing one was invalid (the repo changed).
