### PR TITLE
#385, show error message if a packID to be added contains metadata

### LINKED ISSUE #385: [cpackget] Unable to download a pack file that contains the build identifier
**Describe the bug**

Imagine a pack index file that contains a pack and the pack file contains the build identifier. Example:
``` xml
<pdsc url="https://www.keil.com/pack/" vendor="ARM" name="CMSIS" version="6.1.0+foo" />
```

Then we try to install it using cpackget:

```
cpackget add --verbose ARM::CMSIS@6.1.0+foo
``` 

The command would generate output that ends with:

```
D: bad status: 404
E: "https://www.keil.com/pack/ARM.CMSIS.6.1.0.pack": bad request
```

But it should try to download `https://www.keil.com/pack/ARM.CMSIS.6.1.0+foo.pack` instead.
In the .pdsc file embedded in the .pack file, the release node is:
```xml
  <releases>
    <release date="2024-02-30" version="6.1.0+foo">
      the change log entries...
   </release>
  </releases>
```

**To Reproduce**
See above.

**Expected behavior**
The pack file should be downloaded.

**Environment (please complete the following information):**
 - OS: any
 - Version 2.1.4?

**Additional context**
Obviously, we did not see the problem with the ARM.CMSIS.6.1.0 pack, but an internal pack. The steps above should highlight the question regardless of the pack name.
The .pack files is named including the metadata/build identifier on the server.

### PR DESCRIPTION
**Pull request by bgn42**
## Fixes
#385 

## Checklist

- [x] 🤖 This change is covered by unit tests (if applicable).
- [x] 🤹 Manual testing has been performed (if necessary).
- [x] 🛡️ Security impacts have been considered (if relevant).
- [x] 📖 Documentation updates are complete (if required).
- [ ] 🧠 Third-party dependencies and TPIP updated (if required).

### CODE REVIEW

File: cmd/errors/errors.go [hunk 1]
```diff
@@ -27,8 +27,9 @@ func AlreadyLogged(err error) bool {
 
 var (
 	// Errors related to package file name
-	ErrBadPackName = errors.New("bad pack name: it must be either a PackID:  packVendor::Pack[@version|@~version|@^version|@>=version] or a local Pack file: <path>/Vendor.Pack.version.pack or a local Pack Description file: <path>/Vendor.Pack.pdsc")
-	ErrBadPackURL  = errors.New("bad pack url: the url provided for this pack is malformed")
+	ErrBadPackName    = errors.New("bad pack name: it must be either a PackID:  packVendor::Pack[@version|@~version|@^version|@>=version] or a local Pack file: <path>/Vendor.Pack.version.pack or a local Pack Description file: <path>/Vendor.Pack.pdsc")
+	ErrBadPackURL     = errors.New("bad pack url: the url provided for this pack is malformed")
```
Comment (jkrech) [inline cmd/errors/errors.go:31]: it would be good if could specify what we are expecting.
`https://<something>/packVendor.Pack.version.pack`

File: cmd/errors/errors.go [hunk 2]
```diff
@@ -27,8 +27,9 @@ func AlreadyLogged(err error) bool {
...
+	ErrBadPackVersion = errors.New("bad pack version: cannot add a version with build metadata")
```
Comment (jkrech) [inline cmd/errors/errors.go:32]: bad pack version has '"%s"' build metadata
expected: <major>.<minor>.<patch>[-<pre-release>]

**Review by jkrech — CHANGES_REQUESTED** [review]
would be good to identify the `+meta` part of the version and print it as part of the message.

**Review by jkrech — APPROVED** [review]
LGTM
